#!/bin/sh
sudo apt -q update 
ALL_PACKAGES=$(apt-cache -q search multiflexi | awk '{print $1}')
echo $ALL_PACKAGES

# define blacklist of packages to be grep'ed out

OPTIONAL_PACKAGES="
multiflexi-all
multiflexi-mysql
multiflexi-pgsql
multiflexi-sqlite
multiflexi-podman
"

BLOCKED_PACKAGES="
multiflexi-pohoda-client-config
"

# Remove optional packages from the list of all packages

for i in $OPTIONAL_PACKAGES
do
    ALL_PACKAGES=$(echo $ALL_PACKAGES | sed "s/$i//g")
done

# Remove blocked packages from the list of all packages

for i in $BLOCKED_PACKAGES
do
    ALL_PACKAGES=$(echo $ALL_PACKAGES | sed "s/$i//g")
done


echo
echo "######################### Packages included ######################################"
echo
echo $ALL_PACKAGES | sed "s/ /\n/g"
echo
echo "##################################################################################"

# Replace spaces with commas in the list of all packages

ALL_PACKAGES=$(echo $ALL_PACKAGES | sed "s/ /,/g")


# Replace Depends: in file debian/control by $ALL_PACKAGES
sed "s/^Depends:.*/Depends: $ALL_PACKAGES/g" debian/control.template > debian/control

# Cut everything after ## Packages included in README.md
sed -i '/## Packages included/,$d' README.md

# Update README.md file with current ALL_PACKAGES contents
echo >> README.md
echo "## Packages included" >> README.md
echo >> README.md
echo "| Name | URL |" >> README.md
echo "|------|-----|" >> README.md

for package in $(echo "$ALL_PACKAGES" | tr ',' '\n'); do
    url=$(aptitude show $package | grep -m1 '^Homepage:' | awk '{print $2}')
    echo "| $package | $url |" >> README.md
done

echo >> README.md
echo "Please refer to the individual package documentation for more information." >> README.md

sudo chmod 644 debian/control
sudo chown jenkins:jenkins debian/control
